server:
  port: 7571
  servlet:
    context-path: /demo/user
spring:
  application:
    name: demo-user
  config:
    import: nacos:u_service.yml?group=demo_u
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

cus:
  user:
    timeout: 600000 # 10min
    githubUserUrl: https://api.github.com/user
    githubAuthUrl: https://github.com/login/oauth/authorize
    githubAccTokenUrl: https://github.com/login/oauth/access_token
    githubClientId: ${GIT_CLIENT_ID}
    GIT_SECRET: ${GIT_SECRET}

logging:
  file:
    name: logs/user-app.log
  level:
    root: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
