server:
  port: 7573

spring:
  application:
    name: demo-gateway
  config:
    import: nacos:u_service.yml?group=demo_u
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.76.165:8848
        namespace: public
      config:
        server-addr: 47.106.76.165:8848
        namespace: public
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务路由
        - id: demo-user
          uri: lb://demo-user
          predicates:
            - Path=/demo/user/**
          filters:
            - StripPrefix=0  # 不剥离前缀，保持完整路径  
        # 产品服务路由
        - id: demo-product
          uri: lb://demo-product
          predicates:
            - Path=/demo/product/**
          filters:
            - StripPrefix=0  # 不剥离前缀，保持完整路径
    sentinel:
      transport:
        dashboard: 47.106.76.165:8080
      eager: true
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: {"code": 429, "message": "服务繁忙，请稍后重试"}

logging:
  level:
    com.liz: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
