server:
  port: 7573

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_URL}
        namespace: public
      config:
        server-addr: ${NACOS_URL}
        namespace: public
        file-extension: yml
    gateway:
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/demo/user/**
            - name: AuthFilter
        # 产品服务路由
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/demo/product/**

logging:
  level:
    com.liz: info
    org.springframework.cloud.gateway: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
