server:
  port: 7573
  servlet:
    context-path: /demo
spring:
  application:
    name: demo-product
  config:
    import: nacos:p_service.yml?group=demo_p
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
cus:
  product:
    timeout: 600000 # 10min
    githubUserUrl: https://api.github.com/user
    githubAuthUrl: https://github.com/login/oauth/authorize
    githubAccTokenUrl: https://github.com/login/oauth/access_token
    githubClientId: ${GIT_CLIENT_ID}
logging:
  file:
    name: logs/app.log           # 日志文件路径（相对项目根目录）
  level:
    root: INFO                  # 全局日志级别
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"  # 日志格式